env:
  PORT: 3600
  ROOT_URL: http://192.168.0.195:3600/
  ROOT_URL_INTRANET: http://192.168.0.195:3600/
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/qhd-beta
public:
  cfs:
    store: "local"
    local:
      folder: "/srv/steedos"
plugins: 
  - "@steedos/app-contracts"
  - "D://GitHub//steedos-plugin-jsreport"