env:
  PORT: 3600
  ROOT_URL: http://127.0.0.1:3600/
  ROOT_URL_INTRANET: http://127.0.0.1:3600/
datasources:
  default:
    connection:
      url: mongodb://192.168.0.77/qhd-beta
public:
  cfs:
    store: "local"
    local:
      folder: "/srv/steedos"
plugins: ["D://GitHub//steedos-plugin-jsreport"]